<a href="https://colab.research.google.com/github/amogh-2/py_torch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch_Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [2]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim


0

In [3]:
#Get tensor back as int
scalar.item()

7

In [4]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [7]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX[1]

tensor([3, 4])

In [10]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [11]:
TENSORS.shape

torch.Size([1, 3, 2])

In [12]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [13]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.9718, 0.3168, 0.5462, 0.4972],
        [0.7692, 0.4327, 0.8254, 0.9522],
        [0.3146, 0.8679, 0.9264, 0.0333]])

In [14]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)