## 00.Pytorch_Fundamentals

In [71]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu126


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [72]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim


0

In [73]:
#Get tensor back as int
scalar.item()

7

In [74]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [75]:
vector.ndim

1

In [76]:
vector.shape

torch.Size([3])

In [77]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
MATRIX[1]

tensor([3, 4])

In [80]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [81]:
TENSORS.shape

torch.Size([1, 3, 2])

In [82]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [83]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.6132, 0.5644, 0.5548, 0.0108],
        [0.6341, 0.0455, 0.4480, 0.3321],
        [0.6643, 0.2683, 0.7686, 0.4067]])

In [84]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [85]:
random = torch.rand(3,4,2)
random

tensor([[[0.2054, 0.9938],
         [0.6267, 0.3133],
         [0.2007, 0.1293],
         [0.9160, 0.1370]],

        [[0.7130, 0.0113],
         [0.3577, 0.4281],
         [0.1215, 0.9128],
         [0.8907, 0.0689]],

        [[0.3262, 0.4066],
         [0.8062, 0.8262],
         [0.3732, 0.1625],
         [0.0637, 0.0828]]])

###Zeroes and ones

In [86]:
#Create a tensor of all zeroes
zero=torch.zeros(2,3)
#Create a tensor of all ones
ones=torch.ones(2,3)
zero,ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

###Creating a range of tensors and Tensors-like

In [87]:
a_range=torch.arange(start=0,end=10,step=2)
a_range

tensor([0, 2, 4, 6, 8])

In [88]:
similar_above= torch.zeros_like(a_range)
similar_above

tensor([0, 0, 0, 0, 0])

In [89]:
###Tensors Dimensions
float_32_tensor=torch.tensor([[3.0,4.0,5.0,6.0],
                              [1.2,3.4,5.5,1.4]],
                            dtype=torch.float32,
                            device=None,
                             requires_grad=False)
float_32_tensor

tensor([[3.0000, 4.0000, 5.0000, 6.0000],
        [1.2000, 3.4000, 5.5000, 1.4000]])

In [90]:
###Attributes of tensor 
#Datatype, shape and  device of a tensor
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2, 4]), device(type='cpu'))

In [91]:
###Manipulating Tensors
#Addition
#Substraction
#Multiplication (element wise)
#Division
tensor_1=torch.tensor([[1,2,3,4],
                       [2,3,1,3]])
tensor_2=torch.tensor([2,3,4,5])

In [92]:
#Addition
tensor_1+tensor_2,tensor_1.shape,tensor_2.shape

(tensor([[3, 5, 7, 9],
         [4, 6, 5, 8]]),
 torch.Size([2, 4]),
 torch.Size([4]))

In [93]:
#Multiplication and Division
tensor_1*tensor_2, tensor_2/tensor_1

(tensor([[ 2,  6, 12, 20],
         [ 4,  9,  4, 15]]),
 tensor([[2.0000, 1.5000, 1.3333, 1.2500],
         [1.0000, 1.0000, 4.0000, 1.6667]]))

In [94]:
#Matrix Multiplication
#Inner dimensions must match
#Resulting matrix has the shape of the outer dimensions
torch.matmul(tensor_1,tensor_2)

tensor([40, 32])

In [95]:
#Matrix Multiplication by hand
value=0
for i in range(len(tensor_1)):
    value+=tensor_1[i]*tensor_2[i]
value

tensor([ 8, 13,  9, 17])

In [96]:
tensor_a=torch.tensor([[1,2],
                 [3,4],
                 [5,7]])
tensor_a.shape


torch.Size([3, 2])

In [97]:
###To solve the tensor shape issue. We can Transpose one of the tensors
##A Transpose switches the axes and dimensions of a tensor
tensor_a.T,tensor_a.T.shape

(tensor([[1, 3, 5],
         [2, 4, 7]]),
 torch.Size([2, 3]))

###Finding the min, max, mean, sum, e.t.c (Tensor aggregation)

In [98]:
#Create a Tensor
x=torch.tensor([3,4,8,1])

In [99]:
#Find the min and max
x.min(), x.max()

(tensor(1), tensor(8))

In [100]:
#Find the mean
torch.mean(x,dtype=torch.float32)

tensor(4.)

In [101]:
#Find the sum
x.sum()

tensor(16)

##Position at which min and max

In [102]:
x.argmin(),x.argmax()

(tensor(3), tensor(2))

##Reshaping, Stacking, Squeezing and Unsqueezing tensors

*Reshaping- reshapes an input tensor to a defined shape

*view- return the view of an input tensor of certain shape but keep the same memory as original tensor

*stacking- combines multiple tensors on top of each other (vstack) or side by side (hstack)

*squeeze- removes all one dimensions from a tensor

*unsqueeze- adds a one dimensions from a targer tensor

*permute- return a view of the input with dimensions permuted (swapped) in a certain way

In [103]:
#Create a tensor
x=torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
#Reshape
reshaped_x=x.reshape(2,5)
reshaped_x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [105]:
#Change the view
z=x.view(2,5)
z

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [106]:
#While changing dim with view changing z changes x aswell. Eg:
z[:0]= 5
z,x.reshape(1,10)

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [107]:
###Stack tensors on top of each other
x_stacked=torch.stack([x,x,x],dim=1)
x_stacked   


tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [108]:
###Squeeze Tensors
x=torch.zeros(1,2,3,2)
y=torch.squeeze(x)
x.size(),y.size()


(torch.Size([1, 2, 3, 2]), torch.Size([2, 3, 2]))

In [110]:
x

tensor([[0.2520, 0.7180, 0.1838],
        [0.4317, 0.4517, 0.8723]])

In [112]:
###Unsqueeze Tensors
x=torch.rand(2,3)
x.size()


torch.Size([2, 3])

In [111]:
y=torch.unsqueeze(x, dim=2)
y.size()


torch.Size([2, 3, 1])

In [69]:
y

tensor([[[0.4721],
         [0.4030],
         [0.5667]],

        [[0.5941],
         [0.5388],
         [0.1029]]])