## 00.Pytorch_Fundamentals

In [115]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu126


In [116]:
###Check for GPU access
torch.cuda.is_available()

False

In [167]:
device_to_use= 'cuda' if torch.cuda.is_available() else 'cpu'
device_to_use

'cpu'

In [169]:
tensor=torch.tensor([1,2,3])
print(tensor.device)
tensor=tensor.to(device_to_use)


cpu


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [118]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim


0

In [119]:
#Get tensor back as int
scalar.item()

7

In [120]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [121]:
vector.ndim

1

In [122]:
vector.shape

torch.Size([3])

In [123]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [124]:
MATRIX.shape

torch.Size([2, 2])

In [125]:
MATRIX[1]

tensor([3, 4])

In [126]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [127]:
TENSORS.shape

torch.Size([1, 3, 2])

In [128]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [129]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739]])

In [130]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [131]:
random = torch.rand(3,4,2)
random

tensor([[[0.8016, 0.3649],
         [0.6286, 0.9663],
         [0.7687, 0.4566],
         [0.5745, 0.9200]],

        [[0.3230, 0.8613],
         [0.0919, 0.3102],
         [0.9536, 0.6002],
         [0.0351, 0.6826]],

        [[0.3743, 0.5220],
         [0.1336, 0.9666],
         [0.9754, 0.8474],
         [0.8988, 0.1105]]])

###Zeroes and ones

In [132]:
#Create a tensor of all zeroes
zero=torch.zeros(2,3)
#Create a tensor of all ones
ones=torch.ones(2,3)
zero,ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

###Creating a range of tensors and Tensors-like

In [133]:
a_range=torch.arange(start=0,end=10,step=2)
a_range

tensor([0, 2, 4, 6, 8])

In [134]:
similar_above= torch.zeros_like(a_range)
similar_above

tensor([0, 0, 0, 0, 0])

In [135]:
###Tensors Dimensions
float_32_tensor=torch.tensor([[3.0,4.0,5.0,6.0],
                              [1.2,3.4,5.5,1.4]],
                            dtype=torch.float32,
                            device=None,
                             requires_grad=False)
float_32_tensor

tensor([[3.0000, 4.0000, 5.0000, 6.0000],
        [1.2000, 3.4000, 5.5000, 1.4000]])

In [136]:
###Attributes of tensor 
#Datatype, shape and  device of a tensor
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2, 4]), device(type='cpu'))

In [137]:
###Manipulating Tensors
#Addition
#Substraction
#Multiplication (element wise)
#Division
tensor_1=torch.tensor([[1,2,3,4],
                       [2,3,1,3]])
tensor_2=torch.tensor([2,3,4,5])

In [138]:
#Addition
tensor_1+tensor_2,tensor_1.shape,tensor_2.shape

(tensor([[3, 5, 7, 9],
         [4, 6, 5, 8]]),
 torch.Size([2, 4]),
 torch.Size([4]))

In [139]:
#Multiplication and Division
tensor_1*tensor_2, tensor_2/tensor_1

(tensor([[ 2,  6, 12, 20],
         [ 4,  9,  4, 15]]),
 tensor([[2.0000, 1.5000, 1.3333, 1.2500],
         [1.0000, 1.0000, 4.0000, 1.6667]]))

In [140]:
#Matrix Multiplication
#Inner dimensions must match
#Resulting matrix has the shape of the outer dimensions
torch.matmul(tensor_1,tensor_2)

tensor([40, 32])

In [141]:
#Matrix Multiplication by hand
value=0
for i in range(len(tensor_1)):
    value+=tensor_1[i]*tensor_2[i]
value

tensor([ 8, 13,  9, 17])

In [142]:
tensor_a=torch.tensor([[1,2],
                 [3,4],
                 [5,7]])
tensor_a.shape


torch.Size([3, 2])

In [143]:
###To solve the tensor shape issue. We can Transpose one of the tensors
##A Transpose switches the axes and dimensions of a tensor
tensor_a.T,tensor_a.T.shape

(tensor([[1, 3, 5],
         [2, 4, 7]]),
 torch.Size([2, 3]))

###Finding the min, max, mean, sum, e.t.c (Tensor aggregation)

In [144]:
#Create a Tensor
x=torch.tensor([3,4,8,1])

In [145]:
#Find the min and max
x.min(), x.max()

(tensor(1), tensor(8))

In [146]:
#Find the mean
torch.mean(x,dtype=torch.float32)

tensor(4.)

In [147]:
#Find the sum
x.sum()

tensor(16)

##Position at which min and max

In [148]:
x.argmin(),x.argmax()

(tensor(3), tensor(2))

##Reshaping, Stacking, Squeezing and Unsqueezing tensors

*Reshaping- reshapes an input tensor to a defined shape

*view- return the view of an input tensor of certain shape but keep the same memory as original tensor

*stacking- combines multiple tensors on top of each other (vstack) or side by side (hstack)

*squeeze- removes all one dimensions from a tensor

*unsqueeze- adds a one dimensions from a targer tensor

*permute- return a view of the input with dimensions permuted (swapped) in a certain way

In [149]:
#Create a tensor
x=torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
#Reshape
reshaped_x=x.reshape(2,5)
reshaped_x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [151]:
#Change the view
z=x.view(2,5)
z

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [152]:
#While changing dim with view changing z changes x aswell. Eg:
z[:0]= 5
z,x.reshape(1,10)

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [153]:
###Stack tensors on top of each other
x_stacked=torch.stack([x,x,x],dim=1)
x_stacked   


tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [154]:
###Squeeze Tensors
x=torch.zeros(1,2,3,2)
y=torch.squeeze(x)
x.size(),y.size()


(torch.Size([1, 2, 3, 2]), torch.Size([2, 3, 2]))

In [155]:
###Unsqueeze Tensors
x=torch.rand(2,3)
y=torch.unsqueeze(x, dim=0)
print(y.size(),x.size())
print(x,"\n",y)


torch.Size([1, 2, 3]) torch.Size([2, 3])
tensor([[0.4563, 0.9719, 0.3968],
        [0.1496, 0.4743, 0.9973]]) 
 tensor([[[0.4563, 0.9719, 0.3968],
         [0.1496, 0.4743, 0.9973]]])


In [156]:
###Permute Tensors
x=torch.rand(2,1,3)
print(torch.permute(x, (1,0,2)).shape) ### the values in the bracket are indexes of x. Permute puts x[1] in x[0], x[0] in x[2]
x.shape

torch.Size([1, 2, 3])


torch.Size([2, 1, 3])

In [157]:
#Eg of permute:
x=torch.rand(224,224,3) #[height, width, color channels]
x_permuted=torch.permute(x,(2,0,1))
print(x.shape,
      x_permuted.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])


In [158]:
x[0,0,0]=5
x[0,0,0]

tensor(5.)

###Indexing (Selecting data from Tensors)

In [159]:
#Create a Tensor
x=torch.arange(1.0,10.0).reshape(1,3,3)
x,x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [160]:
print(x[0][2][1],x[0,2,1])
print(x[:,:,1].reshape(3,1))#print 0th value of all dimensions
#To return 3,6,9
x[:,:,2]

tensor(8.) tensor(8.)
tensor([[2.],
        [5.],
        [8.]])


tensor([[3., 6., 9.]])

###Pytorch Tensors and Numpy

In [161]:
#Data from NumPy to Pytorch Tensors
x_np=np.arange(1.0,8,2)
x_tensor=torch.from_numpy(x_np).type(torch.float32)
x_np.dtype,x_tensor.dtype,x.dtype #numpy's default data type is float 64, tensor's is float32

(dtype('float64'), torch.float32, torch.float32)

In [162]:
#Data from Pytorch Tensors to NumPy 
y_tensor=torch.ones(4,dtype=torch.int32)
y_np=y_tensor.numpy()
y_tensor,y_np

(tensor([1, 1, 1, 1], dtype=torch.int32), array([1, 1, 1, 1], dtype=int32))

###Reproducibility (Trying to take random out of random) 

In [163]:
#Create two random Tensors
random_x=torch.rand(3,2)
random_y=torch.rand(3,2)
random_x,random_y

(tensor([[0.2313, 0.2927],
         [0.3386, 0.3708],
         [0.0831, 0.0944]]),
 tensor([[0.6568, 0.7708],
         [0.1053, 0.1467],
         [0.1932, 0.9118]]))

In [164]:
#Set random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
RANDOM_SEED=42
random_x=torch.rand(3,2)
torch.manual_seed(RANDOM_SEED)
random_y=torch.rand(3,2)
print(random_x,'\n',random_y)
print(random_x==random_y)


tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]]) 
 tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[True, True],
        [True, True],
        [True, True]])
