## 00.Pytorch_Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu126


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [2]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim


0

In [3]:
#Get tensor back as int
scalar.item()

7

In [4]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([3])

In [7]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
MATRIX[1]

tensor([3, 4])

In [10]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [11]:
TENSORS.shape

torch.Size([1, 3, 2])

In [12]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [13]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor


tensor([[8.4531e-01, 2.0482e-01, 1.2579e-01, 4.9246e-01],
        [3.3678e-01, 8.6536e-01, 1.4079e-01, 6.3123e-02],
        [6.0739e-01, 7.0173e-04, 8.3985e-01, 6.8496e-01]])

In [14]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
random = torch.rand(3,4,2)
random

tensor([[[0.0493, 0.9098],
         [0.6342, 0.2126],
         [0.3394, 0.0998],
         [0.4534, 0.3258]],

        [[0.9696, 0.2512],
         [0.2867, 0.5630],
         [0.2020, 0.2443],
         [0.0440, 0.0496]],

        [[0.6837, 0.0316],
         [0.0078, 0.0832],
         [0.4221, 0.8059],
         [0.0687, 0.5435]]])

###Zeroes and ones

In [16]:
#Create a tensor of all zeroes
zero=torch.zeros(2,3)
#Create a tensor of all ones
ones=torch.ones(2,3)
zero,ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

###Creating a range of tensors and Tensors-like

In [17]:
a_range=torch.arange(start=0,end=10,step=2)
a_range

tensor([0, 2, 4, 6, 8])

In [18]:
similar_above= torch.zeros_like(a_range)
similar_above

tensor([0, 0, 0, 0, 0])

In [19]:
###Tensors Dimensions
float_32_tensor=torch.tensor([[3.0,4.0,5.0,6.0],
                              [1.2,3.4,5.5,1.4]],
                            dtype=torch.float32,
                            device=None,
                             requires_grad=False)
float_32_tensor

tensor([[3.0000, 4.0000, 5.0000, 6.0000],
        [1.2000, 3.4000, 5.5000, 1.4000]])

In [20]:
###Attributes of tensor 
#Datatype, shape and  device of a tensor
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2, 4]), device(type='cpu'))

In [21]:
###Manipulating Tensors
#Addition
#Substraction
#Multiplication (element wise)
#Division
tensor_1=torch.tensor([[1,2,3,4],
                       [2,3,1,3]])
tensor_2=torch.tensor([2,3,4,5])

In [22]:
#Addition
tensor_1+tensor_2,tensor_1.shape,tensor_2.shape

(tensor([[3, 5, 7, 9],
         [4, 6, 5, 8]]),
 torch.Size([2, 4]),
 torch.Size([4]))

In [23]:
#Multiplication and Division
tensor_1*tensor_2, tensor_2/tensor_1

(tensor([[ 2,  6, 12, 20],
         [ 4,  9,  4, 15]]),
 tensor([[2.0000, 1.5000, 1.3333, 1.2500],
         [1.0000, 1.0000, 4.0000, 1.6667]]))

In [24]:
#Matrix Multiplication
#Inner dimensions must match
#Resulting matrix has the shape of the outer dimensions
torch.matmul(tensor_1,tensor_2)

tensor([40, 32])

In [25]:
#Matrix Multiplication by hand
value=0
for i in range(len(tensor_1)):
    value+=tensor_1[i]*tensor_2[i]
value

tensor([ 8, 13,  9, 17])

In [26]:
tensor_a=torch.tensor([[1,2],
                 [3,4],
                 [5,7]])
tensor_a.shape


torch.Size([3, 2])

In [27]:
###To solve the tensor shape issue. We can Transpose one of the tensors
##A Transpose switches the axes and dimensions of a tensor
tensor_a.T,tensor_a.T.shape

(tensor([[1, 3, 5],
         [2, 4, 7]]),
 torch.Size([2, 3]))

###Finding the min, max, mean, sum, e.t.c (Tensor aggregation)

In [28]:
#Create a Tensor
x=torch.tensor([3,4,8,1])

In [29]:
#Find the min and max
x.min(), x.max()

(tensor(1), tensor(8))

In [30]:
#Find the mean
torch.mean(x,dtype=torch.float32)

tensor(4.)

In [31]:
#Find the sum
x.sum()

tensor(16)

##Position at which min and max

In [32]:
x.argmin(),x.argmax()

(tensor(3), tensor(2))

##Reshaping, Stacking, Squeezing and Unsqueezing tensors

*Reshaping- reshapes an input tensor to a defined shape

*view- return the view of an input tensor of certain shape but keep the same memory as original tensor

*stacking- combines multiple tensors on top of each other (vstack) or side by side (hstack)

*squeeze- removes all one dimensions from a tensor

*unsqueeze- adds a one dimensions from a targer tensor

*permute- return a view of the input with dimensions permuted (swapped) in a certain way

In [33]:
#Create a tensor
x=torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
#Reshape
reshaped_x=x.reshape(2,5)
reshaped_x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [35]:
#Change the view
z=x.view(2,5)
z

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [36]:
#While changing dim with view changing z changes x aswell. Eg:
z[:0]= 5
z,x.reshape(1,10)

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [37]:
###Stack tensors on top of each other
x_stacked=torch.stack([x,x,x],dim=1)
x_stacked   


tensor([[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [38]:
###Squeeze Tensors
x=torch.zeros(1,2,3,2)
y=torch.squeeze(x)
x.size(),y.size()


(torch.Size([1, 2, 3, 2]), torch.Size([2, 3, 2]))

In [52]:
###Unsqueeze Tensors
x=torch.rand(2,3)
y=torch.unsqueeze(x, dim=0)
print(y.size(),x.size())
print(x,"\n",y)


torch.Size([1, 2, 3]) torch.Size([2, 3])
tensor([[0.1323, 0.1239, 0.1421],
        [0.6717, 0.9576, 0.8538]]) 
 tensor([[[0.1323, 0.1239, 0.1421],
         [0.6717, 0.9576, 0.8538]]])


In [60]:
###Permute Tensors
x=torch.rand(2,1,3)
print(torch.permute(x, (1,0,2)).shape) ### the values in the bracket are indexes of x. Permute puts x[1] in x[0], x[0] in x[2]
x.shape

torch.Size([1, 2, 3])


torch.Size([2, 1, 3])

In [61]:
#Eg of permute:
x=torch.rand(224,224,3) #[height, width, color channels]
x_permuted=torch.permute(x,(2,0,1))
print(x.shape,
      x_permuted.shape)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])
