## 00.Pytorch_Fundamentals

In [31]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu126


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [32]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim


0

In [33]:
#Get tensor back as int
scalar.item()

7

In [34]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [35]:
vector.ndim

1

In [36]:
vector.shape

torch.Size([3])

In [37]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [38]:
MATRIX.shape

torch.Size([2, 2])

In [39]:
MATRIX[1]

tensor([3, 4])

In [40]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [41]:
TENSORS.shape

torch.Size([1, 3, 2])

In [42]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [43]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.9361, 0.0043, 0.7558, 0.5671],
        [0.4206, 0.3839, 0.2213, 0.0882],
        [0.0472, 0.0524, 0.6338, 0.6681]])

In [44]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [45]:
random = torch.rand(3,4,2)
random

tensor([[[0.0948, 0.9641],
         [0.1888, 0.9266],
         [0.8194, 0.2537],
         [0.3813, 0.3774]],

        [[0.1099, 0.3795],
         [0.5236, 0.3768],
         [0.4016, 0.7495],
         [0.8888, 0.5104]],

        [[0.2969, 0.3729],
         [0.8364, 0.8682],
         [0.3103, 0.9078],
         [0.4956, 0.8155]]])

###Zeroes and ones

In [46]:
#Create a tensor of all zeroes
zero=torch.zeros(2,3)
#Create a tensor of all ones
ones=torch.ones(2,3)
zero,ones

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

###Creating a range of tensors and Tensors-like

In [47]:
a_range=torch.arange(start=0,end=10,step=2)
a_range

tensor([0, 2, 4, 6, 8])

In [48]:
similar_above= torch.zeros_like(a_range)
similar_above

tensor([0, 0, 0, 0, 0])

In [49]:
###Tensors Dimensions
float_32_tensor=torch.tensor([[3.0,4.0,5.0,6.0],
                              [1.2,3.4,5.5,1.4]],
                            dtype=torch.float32,
                            device=None,
                             requires_grad=False)
float_32_tensor

tensor([[3.0000, 4.0000, 5.0000, 6.0000],
        [1.2000, 3.4000, 5.5000, 1.4000]])

In [50]:
###Attributes of tensor 
#Datatype, shape and  device of a tensor
float_32_tensor.dtype, float_32_tensor.shape, float_32_tensor.device

(torch.float32, torch.Size([2, 4]), device(type='cpu'))

In [51]:
###Manipulating Tensors
#Addition
#Substraction
#Multiplication (element wise)
#Division
tensor_1=torch.tensor([[1,2,3,4],
                       [2,3,1,3]])
tensor_2=torch.tensor([2,3,4,5])

In [52]:
#Addition
tensor_1+tensor_2,tensor_1.shape,tensor_2.shape

(tensor([[3, 5, 7, 9],
         [4, 6, 5, 8]]),
 torch.Size([2, 4]),
 torch.Size([4]))

In [53]:
#Multiplication and Division
tensor_1*tensor_2, tensor_2/tensor_1

(tensor([[ 2,  6, 12, 20],
         [ 4,  9,  4, 15]]),
 tensor([[2.0000, 1.5000, 1.3333, 1.2500],
         [1.0000, 1.0000, 4.0000, 1.6667]]))

In [54]:
#Matrix Multiplication
#Inner dimensions must match
#Resulting matrix has the shape of the outer dimensions
torch.matmul(tensor_1,tensor_2)

tensor([40, 32])

In [55]:
#Matrix Multiplication by hand
value=0
for i in range(len(tensor_1)):
    value+=tensor_1[i]*tensor_2[i]
value

tensor([ 8, 13,  9, 17])

In [56]:
one=torch.tensor([[1,2],
                 [3,4],
                 [5,7]])
one.shape


torch.Size([3, 2])