In [2]:
import torch

In [15]:
###Create a random tensor, Transpose and matrix multiply
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
tensor_1=torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor_2=torch.rand(1,7)
tensor_2_t=tensor_2.reshape(7,1)
torch.matmul(tensor_1,tensor_2_t)

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [16]:
tensor_2,tensor_2_t

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]]),
 tensor([[0.8823],
         [0.9150],
         [0.3829],
         [0.9593],
         [0.3904],
         [0.6009],
         [0.2566]]))