<a href="https://colab.research.google.com/github/amogh-2/py_torch/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch_Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


#Introduction to a Tensors

#Creating Tensors

Pytorch Tensors are created using torch.tensor()



In [4]:
#scalar
scalar=torch.tensor(7)
scalar
scalar.ndim
scalar.dtype


torch.int64

In [5]:
#Get tensor back as int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor([5,3,3])
vector

tensor([5, 3, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
#matrix
MATRIX=torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([3, 4])

In [12]:
#tensor
TENSORS= torch.tensor([[[3,4],[4,5],[6,7]]])
TENSORS

tensor([[[3, 4],
         [4, 5],
         [6, 7]]])

In [13]:
TENSORS.shape

torch.Size([1, 3, 2])

In [14]:
TENSORS[0][1][1]

tensor(5)

##Random Tensors


In [15]:
#Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4,3)
random_tensor


tensor([[[0.2278, 0.6424, 0.5730],
         [0.9961, 0.5440, 0.5234],
         [0.5186, 0.0374, 0.8232],
         [0.0600, 0.2095, 0.5407]],

        [[0.7048, 0.3398, 0.2796],
         [0.4045, 0.6297, 0.8127],
         [0.4833, 0.7810, 0.9392],
         [0.6980, 0.3188, 0.5698]],

        [[0.3422, 0.0708, 0.6111],
         [0.8010, 0.4640, 0.9217],
         [0.7443, 0.7844, 0.8526],
         [0.5318, 0.6992, 0.8343]]])

In [16]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(224,224,3) #height, weight, color channels 3=(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeroes and Ones

In [17]:
#Create a tensor of all zero

zeros = torch.zeros(1,1,3)
zeros

tensor([[[0., 0., 0.]]])

In [18]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [19]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensors and tensors-like

In [20]:
#use torch.arange
arange= torch.arange(0,step=2,end=11)
arange

tensor([ 0,  2,  4,  6,  8, 10])

In [21]:
#Create tensor like
ten_zeros=torch.zeros_like(input=arange)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

###Tensor Data Types
These are the major errors encountered during learning
1. Tensors are not right datatype (use tensor.dtype to check)
2. Tensors are not right shape (use tensor.shape to check)
3. Tensors not on the right device (use tensor.device)

In [22]:
#Float 32 Tensor
float_32_tensor=torch.tensor([[3,6,9],[2,4,8]],
                             dtype= torch.float32, #sets the datatype of the tensor eg: float32, int16, e.t.c
                             device= None, # device type eg: cuda, cpu, e.t.c
                             requires_grad= False # whether or not to track gradients witht the operation
                             )
float_32_tensor.dtype

torch.float32

In [24]:
#float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype, float_32_tensor.dtype, float_16_tensor.shape, float_16_tensor.device

(torch.float16, torch.float32, torch.Size([2, 3]), device(type='cpu'))